[book]
authors = ["TahlonBrahic"]
description = "Filesystem-based module system for Nix"
title = "eris"

[build]
extra-watch-dirs = ["."]

[output.html]
edit-url-template = "https://github.com/TahlonBrahic/eris/edit/main/docs/{path}"
git-repository-url = "https://github.com/TahlonBrahic/eris"
preferred-dark-theme = "ayu"
site-url = "/eris/"
